[package]
edition = "2021"
name = "wayland_protocols"
version = "0.1.3"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.100"
napi = { version = "3.0.0", features = ["anyhow"] }
napi-derive = "3.0.0"
wayland-client = "0.31.11"
wayland-protocols = { version = "0.32.9", features = ["client", "staging"] }

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
