/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class IdleNotifier {
  constructor(opts: IdleNotifierOptions)
  isIdle(): boolean
}

export interface IdleNotifierOptions {
  timeoutMs: number
  onIdled?: () => void
  onResumed?: () => void
}
