name: Upload release metainfo

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Get latest tag
              id: latest_tag
              run: |
                  tag=$(git tag --sort=-creatordate | head -n1)
                  echo "tag=$tag" >> "$GITHUB_OUTPUT"

            - name: Checkout latest tag
              run: git checkout "${{ steps.latest_tag.outputs.tag }}"

            - uses: pnpm/action-setup@v6 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 24
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 24

            - name: Install dependencies
              run: pnpm i

            - name: Update metainfo
              run: pnpm generateMeta
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload metainfo to release
              run: |
                  gh release upload "${{ steps.latest_tag.outputs.tag }}" dist/dev.vencord.Vesktop.metainfo.xml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
